# Deploiement Render.com — https://render.com
# MySQL GRATUIT : utiliser db4free.net (Render n'a pas de MySQL free natif)

services:
  - type: web
    name: vite-gourmand
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: MONGO_URI
        sync: false
